import { dollars } from "@/lib/money";
import { makeCard, makeProperty, makeTax, makeTransport, makeUtility } from "../board";
import type { Card } from "../cards";
import { applyRegionLabels, type GameMap, type GameMapRegion } from "./types";

const spaces = [
  { index: 0, name: "GO", type: "go" as const, lines: ["GO"] },
  makeProperty(1, "Winnipeg", "brown", 60, ["WINNIPEG"]),
  makeCard(2, "Treasure", "treasure", ["TREASURE"]),
  makeProperty(3, "Brandon", "brown", 60, ["BRANDON"]),
  makeTax(4, "Income Tax", 200, ["INCOME TAX"]),
  makeTransport(5, "VIA Rail", 200, ["VIA RAIL"]),
  makeProperty(6, "Regina", "lightblue", 100, ["REGINA"]),
  makeCard(7, "Surprise", "surprise", ["SURPRISE"]),
  makeProperty(8, "Saskatoon", "lightblue", 100, ["SASKATOON"]),
  makeProperty(9, "Moose Jaw", "lightblue", 120, ["MOOSE JAW"]),
  { index: 10, name: "Jail", type: "jail" as const, lines: ["JAIL"] },
  makeProperty(11, "Halifax", "pink", 140, ["HALIFAX"]),
  makeUtility(12, "Hydro One", 150, ["HYDRO ONE"]),
  makeProperty(13, "Dartmouth", "pink", 140, ["DARTMOUTH"]),
  makeProperty(14, "Sydney", "pink", 160, ["SYDNEY"]),
  makeTransport(15, "WestJet YYC", 200, ["WESTJET YYC"]),
  makeProperty(16, "Quebec City", "orange", 180, ["QUEBEC CITY"]),
  makeCard(17, "Treasure", "treasure", ["TREASURE"]),
  makeProperty(18, "Laval", "orange", 180, ["LAVAL"]),
  makeProperty(19, "Montreal", "orange", 200, ["MONTREAL"]),
  { index: 20, name: "Free Parking", type: "free" as const, lines: ["FREE", "PARKING"] },
  makeProperty(21, "Edmonton", "red", 220, ["EDMONTON"]),
  makeCard(22, "Surprise", "surprise", ["SURPRISE"]),
  makeProperty(23, "Red Deer", "red", 220, ["RED DEER"]),
  makeProperty(24, "Calgary", "red", 240, ["CALGARY"]),
  makeTransport(25, "Air Canada YYZ", 200, ["AIR CANADA", "YYZ"]),
  makeProperty(26, "Sudbury", "yellow", 260, ["SUDBURY"]),
  makeProperty(27, "Hamilton", "yellow", 260, ["HAMILTON"]),
  makeUtility(28, "Regional Water", 150, ["REGIONAL", "WATER"]),
  makeProperty(29, "Ottawa", "yellow", 280, ["OTTAWA"]),
  { index: 30, name: "Go To Jail", type: "gotojail" as const, lines: ["GO TO", "JAIL"] },
  makeProperty(31, "Victoria", "green", 300, ["VICTORIA"]),
  makeProperty(32, "Surrey", "green", 300, ["SURREY"]),
  makeCard(33, "Treasure", "treasure", ["TREASURE"]),
  makeProperty(34, "Vancouver", "green", 320, ["VANCOUVER"]),
  makeTransport(35, "BC Ferries", 200, ["BC FERRIES"]),
  makeCard(36, "Surprise", "surprise", ["SURPRISE"]),
  makeProperty(37, "North York", "darkblue", 350, ["NORTH YORK"]),
  makeTax(38, "Luxury Tax", 100, ["LUXURY TAX"]),
  makeProperty(39, "Downtown Toronto", "darkblue", 400, ["DOWNTOWN", "TORONTO"]),
];

const regions: GameMapRegion[] = [
  { id: "brown", name: "Manitoba", spaceIndexes: [1, 3] },
  { id: "lightblue", name: "Saskatchewan", spaceIndexes: [6, 8, 9] },
  { id: "pink", name: "Nova Scotia", spaceIndexes: [11, 13, 14] },
  { id: "orange", name: "Quebec", spaceIndexes: [16, 18, 19] },
  { id: "red", name: "Alberta", spaceIndexes: [21, 23, 24] },
  { id: "yellow", name: "Ontario North", spaceIndexes: [26, 27, 29] },
  { id: "green", name: "British Columbia", spaceIndexes: [31, 32, 34] },
  { id: "darkblue", name: "Toronto", spaceIndexes: [37, 39] },
];

applyRegionLabels(spaces, regions);

const treasure: Card[] = [
  { id: "cad-treasure-1", deck: "treasure", text: "CRA refund cleared.", effect: { type: "collect", amount: dollars(200) } },
  { id: "cad-treasure-2", deck: "treasure", text: "Bank error in your favour.", effect: { type: "collect", amount: dollars(200) } },
  { id: "cad-treasure-3", deck: "treasure", text: "Tim Hortons roll-up-the-rim win.", effect: { type: "collect", amount: dollars(50) } },
  { id: "cad-treasure-4", deck: "treasure", text: "GST/HST credit deposited.", effect: { type: "collect", amount: dollars(100) } },
  { id: "cad-treasure-5", deck: "treasure", text: "You sold your old snowblower on Kijiji.", effect: { type: "collect", amount: dollars(50) } },
  { id: "cad-treasure-6", deck: "treasure", text: "It's your birthday. Every player chips in $10.", effect: { type: "collectFromEach", amount: dollars(10) } },
  { id: "cad-treasure-7", deck: "treasure", text: "Walk-in clinic visit — parking fee and all.", effect: { type: "pay", amount: dollars(100) } },
  { id: "cad-treasure-8", deck: "treasure", text: "School supply fee is due.", effect: { type: "pay", amount: dollars(50) } },
  { id: "cad-treasure-9", deck: "treasure", text: "Landlord raised the rent last minute.", effect: { type: "pay", amount: dollars(150) } },
  { id: "cad-treasure-10", deck: "treasure", text: "Get Out of Jail Free. Keep this card until you need it.", effect: { type: "jailFree" } },
  { id: "cad-treasure-11", deck: "treasure", text: "Caught rolling through a stop sign. Go directly to Jail.", effect: { type: "goToJail" } },
  { id: "cad-treasure-12", deck: "treasure", text: "Head straight to GO.", effect: { type: "moveTo", to: 0, passGoPays: true } },
  { id: "cad-treasure-13", deck: "treasure", text: "Hydro refunded your estimated billing.", effect: { type: "collect", amount: dollars(75) } },
  { id: "cad-treasure-14", deck: "treasure", text: "You won the community rink 50/50. Every player pays you $25.", effect: { type: "collectFromEach", amount: dollars(25) } },
  { id: "cad-treasure-15", deck: "treasure", text: "Ice storm repairs across all your properties.", effect: { type: "repairs", perHouse: dollars(40), perHotel: dollars(115) } },
  { id: "cad-treasure-16", deck: "treasure", text: "Provincial tax refund cleared.", effect: { type: "collect", amount: dollars(20) } },
];

const surprise: Card[] = [
  { id: "cad-surprise-1", deck: "surprise", text: "Black ice — go back three spaces.", effect: { type: "moveBack", spaces: 3 } },
  { id: "cad-surprise-2", deck: "surprise", text: "Head straight to GO.", effect: { type: "moveTo", to: 0, passGoPays: true } },
  { id: "cad-surprise-3", deck: "surprise", text: "Take a trip to Downtown Toronto.", effect: { type: "moveTo", to: 39, passGoPays: true } },
  { id: "cad-surprise-4", deck: "surprise", text: "Pothole damage — new tire required.", effect: { type: "pay", amount: dollars(50) } },
  { id: "cad-surprise-5", deck: "surprise", text: "Advance to the nearest transport hub. Pay double rent, or buy it if nobody owns it.", effect: { type: "nearestTransport", rentMultiplier: 2 } },
  { id: "cad-surprise-6", deck: "surprise", text: "Advance to the nearest transport hub. Pay double rent, or buy it if nobody owns it.", effect: { type: "nearestTransport", rentMultiplier: 2 } },
  { id: "cad-surprise-7", deck: "surprise", text: "Advance to the nearest utility. If owned, roll and pay ten times the total.", effect: { type: "nearestUtility", rentMultiplier: 10 } },
  { id: "cad-surprise-8", deck: "surprise", text: "Snow removal bill.", effect: { type: "pay", amount: dollars(100) } },
  { id: "cad-surprise-9", deck: "surprise", text: "Get Out of Jail Free. Keep this card until you need it.", effect: { type: "jailFree" } },
  { id: "cad-surprise-10", deck: "surprise", text: "Didn't clear your sidewalk in time. Go directly to Jail.", effect: { type: "goToJail" } },
  { id: "cad-surprise-11", deck: "surprise", text: "Advance to Halifax.", effect: { type: "moveTo", to: 11, passGoPays: true } },
  { id: "cad-surprise-12", deck: "surprise", text: "Advance to Surrey.", effect: { type: "moveTo", to: 32, passGoPays: true } },
  { id: "cad-surprise-13", deck: "surprise", text: "Ice storm knocked out the block — repairs on every property.", effect: { type: "repairs", perHouse: dollars(25), perHotel: dollars(100) } },
  { id: "cad-surprise-14", deck: "surprise", text: "Dividends from your cottage rental.", effect: { type: "collect", amount: dollars(150) } },
  { id: "cad-surprise-15", deck: "surprise", text: "You organized the potluck. Pay every player $50.", effect: { type: "payEach", amount: dollars(50) } },
  { id: "cad-surprise-16", deck: "surprise", text: "Condo special assessment levy.", effect: { type: "pay", amount: dollars(75) } },
];

export const canadaMap: GameMap = {
  id: "canada",
  name: "Canada",
  tagline: "Coast to coast to coast.",
  flagEmoji: "🇨🇦",
  theme: "modern",
  currency: "CAD",
  jailLabel: "Jail",
  freeParkingLabel: "Free Parking",
  deckLabels: { treasure: "Treasure", surprise: "Surprise" },
  spaces,
  decks: { treasure, surprise },
  regions,
};
