import { dollars } from "@/lib/money";
import { makeCard, makeProperty, makeTax, makeTransport, makeUtility } from "../board";
import type { Card } from "../cards";
import { applyRegionLabels, type GameMap, type GameMapRegion } from "./types";

const spaces = [
  { index: 0, name: "GO", type: "go" as const, lines: ["GO"] },
  makeProperty(1, "Agege", "brown", 50, ["AGEGE"]),
  makeCard(2, "Owambe", "treasure", ["OWAMBE"]),
  makeProperty(3, "Mushin", "brown", 55, ["MUSHIN"]),
  makeTax(4, "Agbero Levy", 200, ["AGBERO LEVY"]),
  makeTransport(5, "Oshodi Bus Terminal", 190, ["OSHODI BUS", "TERMINAL"]),
  makeProperty(6, "Ojuelegba", "lightblue", 90, ["OJUELEGBA"]),
  makeCard(7, "Village People", "surprise", ["VILLAGE", "PEOPLE"]),
  makeProperty(8, "Yaba", "lightblue", 90, ["YABA"]),
  makeProperty(9, "Surulere", "lightblue", 110, ["SURULERE"]),
  { index: 10, name: "Kirikiri", type: "jail" as const, lines: ["KIRIKIRI"] },
  makeProperty(11, "Ikeja City Mall", "pink", 130, ["IKEJA CITY", "MALL"]),
  makeUtility(12, "NEPA", 140, ["NEPA"]),
  makeProperty(13, "Ogba", "pink", 130, ["OGBA"]),
  makeProperty(14, "Berger", "pink", 150, ["BERGER"]),
  makeTransport(15, "Ojota Motor Park", 190, ["OJOTA MOTOR", "PARK"]),
  makeProperty(16, "Bodija, Ibadan", "orange", 170, ["BODIJA", "IBADAN"]),
  makeCard(17, "Owambe", "treasure", ["OWAMBE"]),
  makeProperty(18, "Ring Road, Benin", "orange", 170, ["RING ROAD", "BENIN"]),
  makeProperty(19, "Independence Layout, Enugu", "orange", 190, ["INDEPENDENCE", "LAYOUT", "ENUGU"]),
  { index: 20, name: "Detty December", type: "free" as const, lines: ["DETTY", "DECEMBER"] },
  makeProperty(21, "Nassarawa GRA, Kano", "red", 210, ["NASSARAWA GRA", "KANO"]),
  makeCard(22, "Village People", "surprise", ["VILLAGE", "PEOPLE"]),
  makeProperty(23, "Old GRA, Port Harcourt", "red", 210, ["OLD GRA", "PORT HARCOURT"]),
  makeProperty(24, "Ikeja GRA", "red", 230, ["IKEJA GRA"]),
  makeTransport(25, "Murtala Muhammed Airport", 190, ["MURTALA", "MUHAMMED", "AIRPORT"]),
  makeProperty(26, "Lekki Phase 1", "yellow", 250, ["LEKKI", "PHASE 1"]),
  makeProperty(27, "Oniru", "yellow", 250, ["ONIRU"]),
  makeUtility(28, "Lagos Water Corporation", 140, ["LAGOS WATER", "CORPORATION"]),
  makeProperty(29, "Wuse II, Abuja", "yellow", 270, ["WUSE II", "ABUJA"]),
  { index: 30, name: "Go To Kirikiri", type: "gotojail" as const, lines: ["GO TO", "KIRIKIRI"] },
  makeProperty(31, "Victoria Island", "green", 290, ["VICTORIA", "ISLAND"]),
  makeProperty(32, "Ikoyi", "green", 290, ["IKOYI"]),
  makeCard(33, "Owambe", "treasure", ["OWAMBE"]),
  makeProperty(34, "Maitama, Abuja", "green", 310, ["MAITAMA", "ABUJA"]),
  makeTransport(35, "Blue Line Rail, Lagos", 190, ["BLUE LINE", "RAIL", "LAGOS"]),
  makeCard(36, "Village People", "surprise", ["VILLAGE", "PEOPLE"]),
  makeProperty(37, "Banana Island", "darkblue", 340, ["BANANA ISLAND"]),
  makeTax(38, "Customs Duty", 100, ["CUSTOMS DUTY"]),
  makeProperty(39, "Eko Atlantic", "darkblue", 380, ["EKO ATLANTIC"]),
];

const regions: GameMapRegion[] = [
  { id: "brown", name: "Lagos Mainland", spaceIndexes: [1, 3] },
  { id: "lightblue", name: "Lagos Bridge", spaceIndexes: [6, 8, 9] },
  { id: "pink", name: "Ikeja", spaceIndexes: [11, 13, 14] },
  { id: "orange", name: "South West", spaceIndexes: [16, 18, 19] },
  { id: "red", name: "Northern GRAs", spaceIndexes: [21, 23, 24] },
  { id: "yellow", name: "Lekki Axis", spaceIndexes: [26, 27, 29] },
  { id: "green", name: "Highbrow", spaceIndexes: [31, 32, 34] },
  { id: "darkblue", name: "Prime", spaceIndexes: [37, 39] },
];

applyRegionLabels(spaces, regions);

const treasure: Card[] = [
  { id: "owambe-1", deck: "treasure", text: "Your aunty sprayed you at the wedding.", effect: { type: "collect", amount: dollars(200) } },
  { id: "owambe-2", deck: "treasure", text: "Bank error in your favour — the alert landed twice.", effect: { type: "collect", amount: dollars(200) } },
  { id: "owambe-3", deck: "treasure", text: "Your side hustle finally paid out.", effect: { type: "collect", amount: dollars(50) } },
  { id: "owambe-4", deck: "treasure", text: "Ajo contribution payout day.", effect: { type: "collect", amount: dollars(100) } },
  { id: "owambe-5", deck: "treasure", text: "You sold your old generator on Jiji.", effect: { type: "collect", amount: dollars(50) } },
  { id: "owambe-6", deck: "treasure", text: "It's your birthday. Every player sprays you $10.", effect: { type: "collectFromEach", amount: dollars(10) } },
  { id: "owambe-7", deck: "treasure", text: "Hospital bill for that malaria.", effect: { type: "pay", amount: dollars(100) } },
  { id: "owambe-8", deck: "treasure", text: "School fees are due.", effect: { type: "pay", amount: dollars(50) } },
  { id: "owambe-9", deck: "treasure", text: "Landlord raised the rent last minute.", effect: { type: "pay", amount: dollars(150) } },
  { id: "owambe-10", deck: "treasure", text: "Free from Kirikiri. Keep this card until you need it.", effect: { type: "jailFree" } },
  { id: "owambe-11", deck: "treasure", text: "Caught driving one-way. Go to Kirikiri. Do not pass GO.", effect: { type: "goToJail" } },
  { id: "owambe-12", deck: "treasure", text: "Head straight to GO.", effect: { type: "moveTo", to: 0, passGoPays: true } },
  { id: "owambe-13", deck: "treasure", text: "NEPA refunded your estimated billing.", effect: { type: "collect", amount: dollars(75) } },
  { id: "owambe-14", deck: "treasure", text: "You won the estate raffle. Every player pays you $25.", effect: { type: "collectFromEach", amount: dollars(25) } },
  { id: "owambe-15", deck: "treasure", text: "Roof repairs across all your properties.", effect: { type: "repairs", perHouse: dollars(40), perHotel: dollars(115) } },
  { id: "owambe-16", deck: "treasure", text: "CRA tax refund cleared.", effect: { type: "collect", amount: dollars(20) } },
];

const surprise: Card[] = [
  { id: "village-1", deck: "surprise", text: "Village people don tie your leg. Go back three spaces.", effect: { type: "moveBack", spaces: 3 } },
  { id: "village-2", deck: "surprise", text: "Head straight to GO.", effect: { type: "moveTo", to: 0, passGoPays: true } },
  { id: "village-3", deck: "surprise", text: "Take a trip to Eko Atlantic.", effect: { type: "moveTo", to: 39, passGoPays: true } },
  { id: "village-4", deck: "surprise", text: "Your car broke down on Third Mainland Bridge.", effect: { type: "pay", amount: dollars(50) } },
  { id: "village-5", deck: "surprise", text: "Advance to the nearest transport hub. Pay double rent, or buy it if nobody owns it.", effect: { type: "nearestTransport", rentMultiplier: 2 } },
  { id: "village-6", deck: "surprise", text: "Advance to the nearest transport hub. Pay double rent, or buy it if nobody owns it.", effect: { type: "nearestTransport", rentMultiplier: 2 } },
  { id: "village-7", deck: "surprise", text: "Advance to the nearest utility. If owned, roll and pay ten times the total.", effect: { type: "nearestUtility", rentMultiplier: 10 } },
  { id: "village-8", deck: "surprise", text: "Fuel scarcity. Pay $100 at the black market.", effect: { type: "pay", amount: dollars(100) } },
  { id: "village-9", deck: "surprise", text: "Free from Kirikiri. Keep this card until you need it.", effect: { type: "jailFree" } },
  { id: "village-10", deck: "surprise", text: "Go to Kirikiri. Do not pass GO.", effect: { type: "goToJail" } },
  { id: "village-11", deck: "surprise", text: "Advance to Ikeja City Mall.", effect: { type: "moveTo", to: 11, passGoPays: true } },
  { id: "village-12", deck: "surprise", text: "Advance to Ikoyi.", effect: { type: "moveTo", to: 32, passGoPays: true } },
  { id: "village-13", deck: "surprise", text: "Your gen packed up. Repairs on every property.", effect: { type: "repairs", perHouse: dollars(25), perHotel: dollars(100) } },
  { id: "village-14", deck: "surprise", text: "Dividends from your cousin's POS business.", effect: { type: "collect", amount: dollars(150) } },
  { id: "village-15", deck: "surprise", text: "You've been elected estate chairman. Pay every player $50.", effect: { type: "payEach", amount: dollars(50) } },
  { id: "village-16", deck: "surprise", text: "Aso-ebi levy for the family owambe.", effect: { type: "pay", amount: dollars(75) } },
];

export const naijaMap: GameMap = {
  id: "naija",
  name: "Naija Edition",
  tagline: "Buy Lagos. Own Naija.",
  flagEmoji: "🇳🇬",
  theme: "modern",
  currency: "CAD",
  jailLabel: "Kirikiri",
  freeParkingLabel: "Detty December",
  deckLabels: { treasure: "Owambe", surprise: "Village People" },
  spaces,
  decks: { treasure, surprise },
  regions,
};
