import { dollars } from "@/lib/money";
import { makeCard, makeChoiceTax, makeProperty, makeTax, makeTransport, makeUtility } from "../board";
import type { Card } from "../cards";
import type { GameMap, GameMapRegion } from "./types";

const spaces = [
  { index: 0, name: "GO", type: "go" as const },
  makeProperty(1, "Agege", "brown", 60),
  makeCard(2, "Treasure", "treasure"),
  makeProperty(3, "Yaba", "brown", 60),
  makeChoiceTax(4, "Income Tax", 200, 10),
  makeTransport(5, "Lagos MMIA", 200),
  makeProperty(6, "Osu, Accra", "lightblue", 100),
  makeCard(7, "Surprise", "surprise"),
  makeProperty(8, "Kumasi", "lightblue", 100),
  makeProperty(9, "Labone", "lightblue", 120),
  { index: 10, name: "Jail", type: "jail" as const },
  makeProperty(11, "Soweto", "pink", 140),
  makeUtility(12, "Global Power Co", 150),
  makeProperty(13, "Sandton", "pink", 140),
  makeProperty(14, "Camps Bay", "pink", 160),
  makeTransport(15, "Heathrow", 200),
  makeProperty(16, "Salvador", "orange", 180),
  makeCard(17, "Treasure", "treasure"),
  makeProperty(18, "Rio de Janeiro", "orange", 180),
  makeProperty(19, "São Paulo", "orange", 200),
  { index: 20, name: "Free Parking", type: "free" as const },
  makeProperty(21, "Manchester", "red", 220),
  makeCard(22, "Surprise", "surprise"),
  makeProperty(23, "Liverpool", "red", 220),
  makeProperty(24, "London", "red", 240),
  makeTransport(25, "Pearson YYZ", 200),
  makeProperty(26, "Toulouse", "yellow", 260),
  makeProperty(27, "Lyon", "yellow", 260),
  makeUtility(28, "Global Water Co", 150),
  makeProperty(29, "Paris", "yellow", 280),
  { index: 30, name: "Go To Jail", type: "gotojail" as const },
  makeProperty(31, "Winnipeg", "green", 300),
  makeProperty(32, "Montreal", "green", 300),
  makeCard(33, "Treasure", "treasure"),
  makeProperty(34, "Toronto", "green", 320),
  makeTransport(35, "JFK", 200),
  makeCard(36, "Surprise", "surprise"),
  makeProperty(37, "San Francisco", "darkblue", 350),
  makeTax(38, "Luxury Tax", 100),
  makeProperty(39, "New York", "darkblue", 400),
];

const regions: GameMapRegion[] = [
  { id: "brown", name: "Nigeria", flagEmoji: "🇳🇬", spaceIndexes: [1, 3] },
  { id: "lightblue", name: "Ghana", flagEmoji: "🇬🇭", spaceIndexes: [6, 8, 9] },
  { id: "pink", name: "South Africa", flagEmoji: "🇿🇦", spaceIndexes: [11, 13, 14] },
  { id: "orange", name: "Brazil", flagEmoji: "🇧🇷", spaceIndexes: [16, 18, 19] },
  { id: "red", name: "United Kingdom", flagEmoji: "🇬🇧", spaceIndexes: [21, 23, 24] },
  { id: "yellow", name: "France", flagEmoji: "🇫🇷", spaceIndexes: [26, 27, 29] },
  { id: "green", name: "Canada", flagEmoji: "🇨🇦", spaceIndexes: [31, 32, 34] },
  { id: "darkblue", name: "United States", flagEmoji: "🇺🇸", spaceIndexes: [37, 39] },
];

const treasure: Card[] = [
  { id: "wt-treasure-1", deck: "treasure", text: "Your startup got acquired.", effect: { type: "collect", amount: dollars(200) } },
  { id: "wt-treasure-2", deck: "treasure", text: "Bank error in your favour.", effect: { type: "collect", amount: dollars(200) } },
  { id: "wt-treasure-3", deck: "treasure", text: "Duty-free souvenirs sold at a markup.", effect: { type: "collect", amount: dollars(50) } },
  { id: "wt-treasure-4", deck: "treasure", text: "Tax refund cleared.", effect: { type: "collect", amount: dollars(100) } },
  { id: "wt-treasure-5", deck: "treasure", text: "You found a forgotten travel card with a balance.", effect: { type: "collect", amount: dollars(50) } },
  { id: "wt-treasure-6", deck: "treasure", text: "It's your birthday. Every player chips in $10.", effect: { type: "collectFromEach", amount: dollars(10) } },
  { id: "wt-treasure-7", deck: "treasure", text: "Travel insurance claim: hospital visit abroad.", effect: { type: "pay", amount: dollars(100) } },
  { id: "wt-treasure-8", deck: "treasure", text: "Visa application fee.", effect: { type: "pay", amount: dollars(50) } },
  { id: "wt-treasure-9", deck: "treasure", text: "Excess baggage fee.", effect: { type: "pay", amount: dollars(150) } },
  { id: "wt-treasure-10", deck: "treasure", text: "Get Out of Jail Free. Keep this card until you need it.", effect: { type: "jailFree" } },
  { id: "wt-treasure-11", deck: "treasure", text: "Overstayed your visa. Go directly to Jail.", effect: { type: "goToJail" } },
  { id: "wt-treasure-12", deck: "treasure", text: "Head straight to GO.", effect: { type: "moveTo", to: 0, passGoPays: true } },
  { id: "wt-treasure-13", deck: "treasure", text: "Utility company overbilled you — refunded.", effect: { type: "collect", amount: dollars(75) } },
  { id: "wt-treasure-14", deck: "treasure", text: "You won a raffle at the airport lounge. Every player pays you $25.", effect: { type: "collectFromEach", amount: dollars(25) } },
  { id: "wt-treasure-15", deck: "treasure", text: "Property maintenance across your whole portfolio.", effect: { type: "repairs", perHouse: dollars(40), perHotel: dollars(115) } },
  { id: "wt-treasure-16", deck: "treasure", text: "Currency exchange worked in your favour.", effect: { type: "collect", amount: dollars(20) } },
];

const surprise: Card[] = [
  { id: "wt-surprise-1", deck: "surprise", text: "Missed connection — go back three spaces.", effect: { type: "moveBack", spaces: 3 } },
  { id: "wt-surprise-2", deck: "surprise", text: "Head straight to GO.", effect: { type: "moveTo", to: 0, passGoPays: true } },
  { id: "wt-surprise-3", deck: "surprise", text: "Take a trip to New York.", effect: { type: "moveTo", to: 39, passGoPays: true } },
  { id: "wt-surprise-4", deck: "surprise", text: "Your rental car broke down.", effect: { type: "pay", amount: dollars(50) } },
  { id: "wt-surprise-5", deck: "surprise", text: "Advance to the nearest transport hub. Pay double rent, or buy it if nobody owns it.", effect: { type: "nearestTransport", rentMultiplier: 2 } },
  { id: "wt-surprise-6", deck: "surprise", text: "Advance to the nearest transport hub. Pay double rent, or buy it if nobody owns it.", effect: { type: "nearestTransport", rentMultiplier: 2 } },
  { id: "wt-surprise-7", deck: "surprise", text: "Advance to the nearest utility. If owned, roll and pay ten times the total.", effect: { type: "nearestUtility", rentMultiplier: 10 } },
  { id: "wt-surprise-8", deck: "surprise", text: "Fuel surcharge at the border.", effect: { type: "pay", amount: dollars(100) } },
  { id: "wt-surprise-9", deck: "surprise", text: "Get Out of Jail Free. Keep this card until you need it.", effect: { type: "jailFree" } },
  { id: "wt-surprise-10", deck: "surprise", text: "Customs flagged your luggage. Go directly to Jail.", effect: { type: "goToJail" } },
  { id: "wt-surprise-11", deck: "surprise", text: "Advance to Soweto.", effect: { type: "moveTo", to: 11, passGoPays: true } },
  { id: "wt-surprise-12", deck: "surprise", text: "Advance to Montreal.", effect: { type: "moveTo", to: 32, passGoPays: true } },
  { id: "wt-surprise-13", deck: "surprise", text: "A storm grounded flights — repairs on every property.", effect: { type: "repairs", perHouse: dollars(25), perHotel: dollars(100) } },
  { id: "wt-surprise-14", deck: "surprise", text: "Dividends from your travel blog sponsorship.", effect: { type: "collect", amount: dollars(150) } },
  { id: "wt-surprise-15", deck: "surprise", text: "You're the trip organizer. Pay every player $50 for the group dinner.", effect: { type: "payEach", amount: dollars(50) } },
  { id: "wt-surprise-16", deck: "surprise", text: "Departure tax.", effect: { type: "pay", amount: dollars(75) } },
];

export const worldTourMap: GameMap = {
  id: "worldTour",
  name: "World Tour",
  tagline: "Eight countries. One board.",
  flagEmoji: "🌍",
  currency: "CAD",
  jailLabel: "Jail",
  freeParkingLabel: "Free Parking",
  deckLabels: { treasure: "Treasure", surprise: "Surprise" },
  spaces,
  decks: { treasure, surprise },
  regions,
};
